### ISSUE TITLE
TODO: add app widget 

### ISSUE THREAD

**Issue by quarck** [quarck/CalendarNotification#118]
Users were asking for a widget for launcher

**Comment by quarck** [comment]
User recommended replicating look of "Calendar Widget" by +1 labs

**Comment by quarck** [comment]
Due to lack of time this would be postponed indefinitely

**Comment by quarck** [comment]
Lack of free time - marked as "help wanted". If someone can implement and do a pull request - welcome

**Comment by quarck** [comment]
Seems useless for this app, closing

**Comment by nascentt** [comment]
I see this is closed marked wontfix, but let me just say, when you have many snoozed tasks, and active reminders, you have to open the app manually to scroll through them all the time.  It'd be nice to have the main app ui as a widget to just list all tasks both snoozed and active on the homescreen.
