### ISSUE TITLE
Add support for Custom Vibration Patterns

### ISSUE THREAD

**Issue by milowg** [quarck/CalendarNotification#159]
How hard would it be to add support for Custom Vibration Patterns? For example, there is no "Single Short" pattern which is what I would prefer. 

Let me know if this is something feasible for you to do, or when you would be able to get to it.
If you have no interest in doing this, I can take a shot although I've never used Kotlin before.

**Comment by quarck** [comment]
Hi, 
Honestly - I don't mind doing it, but I'm very limited on amount of time I can give to this project at the moment. So if you want it earlier -- you can try doing it yourself :) If you have some Java experience, then switching to Kotlin would be quite easy, and it is 100% inter-operable with Java so Java and Kotlin files could be mixed in the same project easily,  - I'm OK if you add some Java code if it is more convenient for you to do it in Java. 

P.S. I'm not a UI developer in general and not Android developer, so my code might be far from ideal Android/Java code. (My main background is in C++ with some peppering by C# (recently)).

**Comment by quarck** [comment]
Another user comment: 
I also love the ability to choose the vibration pattern.  Though I would really like a bit more customisation with it.  I'd prefer either a "short short short short short" or a "Single quite long" which would fall somewhere between "A single long" a "A single very long". Not sure if you could add those or better yet a custom advanced option to type the vibration settings like so "2,1,2,1,2,1,2" in seconds.

**Comment by quarck** [comment]
Previously i didn't did it just because I didn't have much time.  But now it is no longer possible to edit vibration pattern at all after notification channel is created (thats since Oreo). So nothing can't be done here.

**Comment by geobear4** [comment]
@milowg, that would be fantastic!
To tell the truth, I really just miss the old days when phones simply vibrated for the length of the notification sound and that was that. My calendar notification of choice is right around 1/4 of a second. Actually, the sound is an even shorter "tick", but I had to add some silent space at the end, because it was originally SO short that my old phone didn't even have a chance to vibrate.
