### ISSUE TITLE
missing strings for translation

### ISSUE THREAD

**Issue by MaDill** [quarck/CalendarNotification#184]
In the "reminders_section" are two strings I can not find in the language file for translation.
- Custom ringtone with the description
- Custom vibration with the description

Maybe there is no need for a separate translation. Maybe the strings "ringtone_selection", "ringtone_selection_summary" and "vibration_pattern" can be used.

This is a scrennshot how it looks on the German translation.
![screenshot_20161013-084427](https://cloud.githubusercontent.com/assets/7298934/19339232/839083d6-9122-11e6-9995-a4ad1645769a.png)

**Comment by quarck** [comment]
Hi, 

Thank you for reporting that. Sorry for not replying earlier - very very short on time at the moment. I would try moving these into strings.xml in a couple of days. 

Thanks, 
Sergey

**Comment by quarck** [comment]
Sorry it took so long. Was studying and very busy through the year
