### ISSUE TITLE
Feature Request: Outlook Support

### ISSUE THREAD

**Issue by N-Accumbens** [quarck/CalendarNotification#189]
Outlook calendar also lacks snooze reminders, so would it be possible to integrate it the same way Google calendars is integrated?

**Comment by quarck** [comment]
If you are talking about this app: https://play.google.com/store/apps/details?id=com.microsoft.office.outlook, - the answer - unfortunately it is not possible. At least not in the context of this app. 

This app relies on Android standard Calendar Provider service, which hosts events from different sources and so many different calendar apps can access same events. This interface is easily extendable, and that's how Calendar Notifications Plus is implemented. 

Outlook from Microsoft is an app "on its own". It is not exposing anything to other apps. 

One approach that might work in theory - is intercepting notifications using "NotificationListenerService" , but it don't seems to be possible to serialize and replicate notification to make it working as original notification (I did a bit of investigation about it yesterday myself). 

P.S. If your motivation to use Outlook is to become less attached to google ecosystem, I would suggest at least moving task reminders to something like Wunderlist. That app also allows downloading backup of all your data (in a JSON format), so you can always have offline copy of all your entries. And do regular backups of your google calendar entries (there is a link for exporting all your data in the settings), so if they block you for whatever made up reason - you would have data to restore into another fresh account.
