### ISSUE TITLE
Feature request: you should be able to choose the calendars for reminding

### ISSUE THREAD

**Issue by quarck** [quarck/CalendarNotification#19]
$subj

**Comment by Tangram11** [comment]
The old Calendar Snooze (https://play.google.com/store/apps/details?id=com.bitfire.development.calendarsnooze) used to behave as required, but I think the way the Calendar Snooze reminder worked was more like an app forcing its way into the foreground, so when you snoozed or dismissed, it just closed and hence the previous app remained.

It's not a big deal given how good CalendarNotification is now a few of the early bugs have been removed.

**Comment by quarck** [comment]
Thanks, I'll try checking how they've done it with Calendar Snooze.
