### ISSUE TITLE
Use CalendarNotification with Blackberry Android phones?

### ISSUE THREAD

**Issue by sammefford** [quarck/CalendarNotification#191]
I just bought a BlackBerrry Priv and I love it!  One thing I miss, though is my CalendarNotification app and the flexibility to customize the snooze options.  It appears that something BlackBerry is doing makes CalendarNotification disabled.  Is there any way you could make your app work with BlackBerry Android phones?

**Comment by sammefford** [comment]
Nevermind, for some reason Calendar Notifications has now automatically taken over... maybe I just needed to open it for that to happen... strange

**Comment by quarck** [comment]
Glad that it has been resolved. Sorry for late reply - was on holidays.
