### ISSUE TITLE
Incorrect permission request on Android 6

### ISSUE THREAD

**Issue by denis-bogdanas** [quarck/CalendarNotification#194]
Hello, I'm Denis Bogdanas, a research assistant at Oregon Stat University.
I'm working on a tool that automatically introduces runtime permission checks and requests for Android 6 apps. As part of this study I analyzed this app, looking for how permissions are referred in the code.

Your code requests permissions READ_CONTACTS, WRITE_CALENDAR, while in reality it needs READ_CALENDAR, WRITE_CALENDAR. This could make some users wondering why it needs contacts and discourage them from using the app.

Do you think this is an issue and youd you consider to fix it?

best regards,
Denis

**Comment by quarck** [comment]
Hi Denis, 

Many thanks for your feedback. Yes, this is a bug, I believe it was introduced by mistake. Probably I've copy-pasted some sample code and forgot to change some of the permissions. This app never uses contacts access so contacts permission. 
I'll push a fix soon. 

Thanks, 
Sergey
