### ISSUE TITLE
Feature request: Hide event information in lock and/or home screen

### ISSUE THREAD

**Issue by myfreexp** [quarck/CalendarNotification#197]
I think an option to hide the topic/purpose of an event in the notification (and reminder) in the lock and/or home screen might be a good idea.

**Comment by whispy** [comment]
What would bw the difference between this and hiding notifications for the app via Android's built-in notification settings? See for info how to hide notifications from a specific app on yohr lock screen: https://support.google.com/nexus/answer/6111294?hl=en#app_notification_settings

**Comment by quarck** [comment]
I don't think there is a need for special option inside the app itself. Yes, you can hide notification completely or notification content from the lock screen using standard android settings. 
For example my lock screen looks like this: 
![photo_2017-01-16_20-10-29](https://cloud.githubusercontent.com/assets/802696/21997560/e0ad66ba-dc27-11e6-9204-4548ff31db9d.jpg)

**Comment by myfreexp** [comment]
Thanks for the insight, apparently I have to make myself more familiar with the possible settings of Android 6.x. ;) (Used a HTC One M7 with Android 4.4.3 before and am quite new to MM.)

Just tested it, and it does indeed seem to work - great! But only for the lock screen - there is no way to define the behaviour for the home screen, right?

Anyway, for now I can live with it this way.

As a sidenote, all of these devices are lacking of a comprehensive documentation, otherwise I'd most likely not have opened this issue at all.

**Comment by quarck** [comment]
Yes, it would only hide content from the lock screen. Not from the home screen. I'll keep this issue open, so I can add in-app setting later when I have time for that.

**Comment by myfreexp** [comment]
Thanks a lot for response. Even if not everything should be working 100% perfectly already, it's good to know that you're following up. Thumbs up!

**Comment by quarck** [comment]
Copy-paste from #148: 

https://developer.android.com/design/patterns/notifications.html says:

When setting up a secure lock screen, the user can choose to conceal sensitive details from the secure lock screen. In this case the System UI considers the notification's visibility level to figure out what can safely be shown.

To control the visibility level, call Notification.Builder.setVisibility(), and specify one of these values:

VISIBILITY_PUBLIC. Shows the notification's full content. This is the system default if visibility is left unspecified.
VISIBILITY_PRIVATE. On the lock screen, shows basic information about the existence of this notification, including its icon and the name of the app that posted it. The rest of the notification's details are not displayed. A couple of good points to keep in mind are as follows:
If you want to provide a different public version of your notification for the system to display on a secure lock screen, supply a replacement Notification object in the Notification.publicVersion field.
This setting gives your app an opportunity to create a redacted version of the content that is still useful but does not reveal personal information. Consider the example of an SMS app whose notifications include the text of the SMS and the sender's name and contact icon. This notification should be VISIBILITY_PRIVATE, but publicVersion could still contain useful information like "3 new messages" without any other identifying details.
Notification.VISIBILITY_SECRET. Shows only the most minimal information, excluding even the notification's icon.
