### ISSUE TITLE
Action Overflow Menu disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [quarck/CalendarNotification#198]
When i perform this sequence of events, the menu disappears:

Sequence 1:
1. Click on ...
2. Orientation Change

Sequence 2:
1. Click on a notification item in list
2. Click on ...
3. Orientation Change

**Comment by quarck** [comment]
Seems to be a behavior of standard android component. Not fixing at the moment as UI redesign is planned and Action Overflow would no longer be used.
