### ISSUE TITLE
Dialog disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [quarck/CalendarNotification#199]
When i perform these sequences of events, the dialog on screen disappears:

Sequence 1-2:
1. Click on a notification item in list
2. Click on:
a. For a custom period
b. Until specific time and date
3. Orientation Change

**Comment by quarck** [comment]
This one is quite serious as user might loose his progress during rotation (unlike some other similar bugs where it was happening in settings or similar screens).
