### ISSUE TITLE
Spinner menu closes on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [quarck/CalendarNotification#203]
When I perform these sequences of events, the spinner menu on screen disappears:

1. Click on ...
2. Click on Settings
3. Click on reminders
4. Click on Remind interval
5. Click on interval spinner
6. Orientation change

**Comment by quarck** [comment]
Many thanks for reporting these issues - appreciate it. 
I'm the only developer on this project and at the moment I'm very busy with doing part-time college and main job, so I would not be able to fix any issues until end of May. But as soon as I can - I would resume work on this project and fix all the backlog of bugs that were posted here.

**Comment by quarck** [comment]
Seems to be a behavior of standard android control used on that dialog. Not a major issue (if at all) for users.
