### ISSUE TITLE
TODO: Option to 'Mute' LED in quite time

### ISSUE THREAD

**Issue by quarck** [quarck/CalendarNotification#204]
Comment from user: 

I have a question regarding notification exclusion: I entered nightly silence from 22 pm to 7 am next day but I get nevertheless the notification in the status bar (not disturbing) and the LED-notification. Last one disturbs pretty much because LED is shining brightly in the dark sleeping room... Do I misunderstand this option?

**Comment by smichel17** [comment]
I agree with the user that this would be the expected behavior. I do wonder whether it would be better just to do this by default and not provide the option.

**Comment by quarck** [comment]
There are certainly users who prefer it the other way around, so it must be an option.

**Comment by quarck** [comment]
Fixed in the last release
