### ISSUE TITLE
Feature Request: Mute button

### ISSUE THREAD

**Issue by quarck** [quarck/CalendarNotification#207]
> The one thing it's missing though is a "mute" button. With a mute button, you could still see it without snoozing over and over, which gets to be really annoying.

**Comment by Kafakondik** [comment]
How to remove MUTE button on notification panel in new version. Please can you add this setting?
Show MUTE Button  (On/Off)

**Comment by quarck** [comment]
It is under Settings -> Behavior -> "Enable Mute". 
Available since ver 5.0.x. (5.0 and further would be only available on F-Droid, may be will add to amazon app store later, no Google Play updates as they are no longer technically possible)
