### ISSUE TITLE
Undo dismiss

### ISSUE THREAD

**Issue by woj-tek** [quarck/CalendarNotification#211]
Sometimes android notification re-arrange themselves rapidly and instead of opening some notification a 'dismiss' button is hit resulting in closing the notification.

I would be nice to have a list of recently dismissed notifications in the app to revert the mistake.

**Comment by quarck** [comment]
Hi Wojtek, 

Thanks for reporting this. I've seen this issue with rapid re-arrangement of notifications, I would take a look at it at later stage. 
As for list of recently dismissed notifications - it is available, but this functionality is off by default (this is some kind of data collection, I decided not to do it unless user is asking for it). To enable it go to Settings->Behavior and enable option "Keep recently dismissed events". Once it is enabled, it would be an extra menu option "Dismissed events" available from the main screen.

**Comment by quarck** [comment]
P.S. I would keep this ticket open as a reminder about that rapid re-arrangement of notifications. And I'm also thinking of doing this option turned on by default, just need a not a very intrusive way to let users aware about this thing.

**Comment by woj-tek** [comment]
The issue with the re-arrangement feels like applications 'competing' which notification should be at the top and it may not be specific to CalendarNotification.

Thanks for the hint about the option - just what I needed! :-)
