### ISSUE TITLE
ignore events I marked as *not going*

### ISSUE THREAD

**Issue by akostadinov** [quarck/CalendarNotification#218]
Hello, I have many events marked as not going. Can app ignore them and skip notifying me?

**Comment by quarck** [comment]
It is implemented now

**Comment by akostadinov** [comment]
Thank you! Is it now in the version in playstore or not yet released?

**Comment by quarck** [comment]
Not yet released - was planning to do a lot more before the release. 
You could try "early beta" by directly installing APK from here: 

https://www.dropbox.com/sh/jrxyz7su8zyxs40/AAAWaKqgOdvVMphMAvoLwh4sa?dl=0

Please report any bugs if you find something

**Comment by quarck** [comment]
P.S. New settings are under "behavior" menu

**Comment by akostadinov** [comment]
so far the alpha version is working great, thanks a lot!
