### ISSUE TITLE
Bundled notifications support (Android N)

### ISSUE THREAD

**Issue by woj-tek** [quarck/CalendarNotification#227]
Reference: https://medium.com/exploring-android/android-n-introducing-upgraded-notifications-d4dd98a7ca92

Basically all notifications from single application can be bundled into single notification item. At first it was a bit confusing/annoying but I got accustomed to it and now find it very handy.

**Comment by quarck** [comment]
Implemented in 04331588622bf8a3f373200f1104ed029ce8edb3
