### ISSUE TITLE
Merge with Tacere (silence during events)?

### ISSUE THREAD

**Issue by smichel17** [quarck/CalendarNotification#231]
Both apps do similar things (extend the functionality of calendar events); it would be nice if it were all configurable in one place. I also imagine there's a fair amount of duplicate code, so it might be less work to maintain if they were merged.

I'm currently using both and they do not conflict with one another, so this is probably low-priority.

Corresponding issue on the Tacere repo: https://github.com/ciasaboark/Tacere/issues/63

**Comment by quarck** [comment]
It is technically doable, but it would require way too much effort to the value it would provide. These are two totally different (internally) projects designed for different functionality. It is almost the same as creating a new app with the functionality of both.

**Comment by quarck** [comment]
P.S. also there are legal issues with this merge as GPL and BSD license are not that easy to combine in the same project.
