### ISSUE TITLE
snooze on swap and negative snooze presets

### ISSUE THREAD

**Issue by mrnetops** [quarck/CalendarNotification#242]
With snooze on swipe

Settings
-> Notification Settings
-> Snooze on swipe

Calendar Notifications seems to get really confused when the first snooze preset is negative (-2m in my case) and the current time is => what it is trying to snooze to.  It seems to do something funky that ends up with a zillion duplicate notification on my android watch.

In my case, Ideally, I would like to swipe to dismiss the notification, and if the first preset is negative AND we are already on or past that time, then dismiss the alarm.

**Comment by quarck** [comment]
Thanks for reporting this, I'd take a look at this issue by the end of this week.

**Comment by quarck** [comment]
What was happening (I think), is that it was snoozing event until time that was already in the past, so it was firing immediately again and this was causing all sort of confusions for wearable. 

As a workaround / fix, app would now detect this situation and if new snoozed time is already in the past, it would snooze for 1 minute instead. After 1 minute when it fires again, there would be no negative snooze time option anymore. 

I would appreciate if you could try this build to see if it would work: 
https://www.dropbox.com/s/tldy55akxinqmqs/CalendarNotificationPlus_1.4.6-2.apk?dl=0
