### ISSUE TITLE
[Question / Feature request] Disable reminder notifications

### ISSUE THREAD

**Issue by smichel17** [quarck/CalendarNotification#246]
As of the last two versions, there's a new notification:

> <img alt="remindernotification" src="https://user-images.githubusercontent.com/6563664/27597433-56b7b5b8-5b30-11e7-878d-0b7f538d7ff5.png" height="150">

I don't really care about any of that information in the bottom notification, so to me it's just notification clutter that makes it harder to find the reminder that I *do* care about. Is there any way to turn it off entirely?

I noticed in #240 that you mentioned something about this way being more reliable. I assume you're no longer dismissing and refreshing the event notification itself, and doing that through the reminder instead. Maybe it would be possible to still do it that way, but dismiss the reminder notification immediately after it's triggered, so it doesn't stick around in the drawer?

**Comment by quarck** [comment]
This was actually implemented in 939d571bd40687c698a93127214601111e240c23. Will be in the next release soon.
