### ISSUE TITLE
Enhancement Request: Show notifications for items that should have been shown when device was off

### ISSUE THREAD

**Issue by Som30ne** [quarck/CalendarNotification#253]
If you turn the device off or (god forbid) run out of battery,
it would be nice to have the missed events shown/notified.

**Comment by quarck** [comment]
This functionality is already implemented. ("Manual calendar rescan" option must be turned on).

**Comment by Som30ne** [comment]
Thank you for the quick reply.
I did not see this feature mentioned anywhere,
(in any description, or mentioned in the option of "manual scan")
so I thought to request it.

Good to know it's already there.
