### ISSUE TITLE
Enh.Req.: Notification/Reminder repeat - repeat

### ISSUE THREAD

**Issue by Som30ne** [quarck/CalendarNotification#254]
It would be nice to have a repeat pattern for the notification/reminder repeat.
Explanation:
Say you select you want notification/reminder to fire every 1 minute, 6 times.
It would be nice to repeat that pattern every X (say 20) minutes for (5) times.

This means that every 20 minutes the notification pattern would be fired during the next 1:40 hours.
(For example - if you left your phone in your station, and got "stuck" in some meeting,
you would get notification when you get back to your station,
 even if you "missed" the first notification period)

(Hope my explanation was clear/understandable enough)

**Comment by smichel17** [comment]
I'm not convinced Etar needs to do this. The beauty of using Android's native calendar is that other apps can access the same data to do different things. 

@Som30ne does this work well enough for you? Calendar Notifications (Advanced calendar notifications) - https://f-droid.org/app/com.github.quarck.calnotify

**Comment by Som30ne** [comment]
@smichel17 Thanks for the suggestion.
Will try/test and see if the app you linked to fulfills this 
as well as the functionality available in "Calendar Notifications plus" app.

**Comment by quarck** [comment]
As a developer of this app I'm confused as that link is a link to this app on F-Droid.

**Comment by smichel17** [comment]
Wait, crap, I was on mobile and totally misread/thought this was an issue on the Etar repo. Um, carry on.

**Comment by quarck** [comment]
The latest release 1.4.15 (e14888ec2451a41a8c086cd87775d2acd42a6144) would have reminder patterns implemented (currently that build in the process of staged rollout on play store). So I suppose I can close this one.

**Comment by Som30ne** [comment]
The approach taken is a bit different than the one was described,
but - it works for me as well.

Thanks for that !
