### ISSUE TITLE
Ch.Req.: "Dismiss" in notification should be confined

### ISSUE THREAD

**Issue by Som30ne** [quarck/CalendarNotification#255]
Something that I was upset with just a day ago -
A notification popped up,
and I wanted to snooze it for a period of time,
but apparently - I hit an somewhere to the right of the "Dismiss" area -
so instead of showing the snooze options, it was dismissed (...annoying).

I would like the option to confine the "Dismiss" to the minimum necessary,
instead of it being assigned with the whole width of the notification window.

**Comment by quarck** [comment]
Hi, 
Could you please tell me what is your device/model and what version of android is it running? I've never seen 'Dismiss' action being that big, but I don't have too many devices to test with. 

P.S. Also you could enable 'Bin', and it would allow you restoring any accidentally dismissed events.

**Comment by Som30ne** [comment]
Thanks for the reply.
I'm using Samsung S5 w/Android 6.0.1
Build MMB29M.G900FXXU1CPI8 (Not Rooted)

The "bin" hint is a good one.
(Will try it next time)

**Comment by quarck** [comment]
Thank you for the info. Last question (I should have asked earlier): would you be able to provide a screenshot of how that notification looks like? Just for me to get a better understanding of it. 

P.S. Personally I'm using Galaxy S6, and I haven't seen anything like that.

**Comment by Som30ne** [comment]
Tried the "Bin" thing, worked nicely.
Here is link to screenshot:
https://www.dropbox.com/s/pzlgfq2fihvs7ed/Screenshot_2017-08-15-18-51-52%20-%20W-Remark.jpg?dl=1

**Comment by quarck** [comment]
Thanks for the screenshot. I don't know if it would be easy to reduce actual clickable area of 'dismiss' button - it is controlled by the system. I can technically create a custom notification layout, but it would lose consistent lock across multiple devices. 

For reference - on my Device all the notification action buttons are aligned to the right, and clicking on the similar empty space does the same as clicking on the notification itself - e.g. opens the event. 

Anyway - I'd think about this. Probably I could add a custom layout for the notification as an optional setting rather than changing everyone.

**Comment by smichel17** [comment]
@quarck You may be able to cheat the system by adding two other notification actions with " " as their text, that both do the same thing as the notification body. If you're interested in breaking the platform convention, at least.

**Comment by Som30ne** [comment]
@quarck My initial thought was to add another button (or whatever UI element it is) 
set with text like "            "  (whitespace)
next to the "Dismiss" button (or whatever UI element it is).
That way half of the width would be occupied by the "Dismiss" button, and the other half by that other button.
The other button would do the same operation done when hitting the body of the notification.
(I think @smichel17 also described something similar to this)

**Comment by quarck** [comment]
This approach seemed worked, will do some testing on the real device as well and will publish a new build later.

**Comment by Som30ne** [comment]
Just updated the app.
Works as expected.
Many many thanks !!!
