### ISSUE TITLE
Feedback on 1.5.0-a

### ISSUE THREAD

**Issue by kcbaltz** [quarck/CalendarNotification#274]
Some features seem to have been lost or changed in the latest release:

1. If I have multiple notifications, they're getting bundled which makes them harder to address directly without opening the app
2. The "Dismiss" option on the notification seems to be lost although now it appears to support swiping to dismiss.  That's fine
3. There's a new notification telling me how many reminders I've missed.  I don't see the value in this new notification

I've been pretty happy with this app up till now.  If the above changes were all intentional and switches could be added to make them optional, that would be great.  

Also, the app has been crashing when it's running in the background.  I've used the "Submit Feedback", so I'm not opening a separate issue here.

**Comment by nspirov** [comment]
1. That's awful, it was great before. You could individually roll down and press a button on each one.
2. No that's not fine with everyone. I want swipe to be disabled, why remove an option that was already there? Furthermore, having 1. in mind, you swipe ALL notifications together.
