### ISSUE TITLE
Events/appointments are working, reminders are not (from Google Calendar)

### ISSUE THREAD

**Issue by mrbaggins123** [quarck/CalendarNotification#277]
Hi!

Thank you for developing this great app!
I found an issue; as it has not been mentioned by else, I think it is about my phone/configuration, not the app.

I am using Google Calendar, making events (or Appointments - I use the Hungarian version, dunno what the original word is in the english version) and reminders as well.

If I set an event/appointment, it is catched by your app and can be snoozed as intended.
However, the app misses the reminders, an original notification is fired with the sound and appearance from Google Calendar. Tapping on that notification brings up the Calendar page, not the snooze page from your app.

Weird, do you have an idea what could be happening?

I made the modifications you required about the battery optimization. (and after all, I don't think the energy saving is the culprit as the events/appointments work as intended).

I use a Samsung Galaxy A5 (2017) with Android 8.0.0 and the latest Google Calendar.

Thank you if you have the time to answer!

have a good day!

Krisztian

**Comment by quarck** [comment]
Unfortunately google calendar's reminders aren't really in the system calendar,  so third party apps  can't do anything about these reminders.

**Comment by quarck** [comment]
Cant fix - closing
