### ISSUE TITLE
Feature request: Allow regular calendar notifications to appear

### ISSUE THREAD

**Issue by himat** [quarck/CalendarNotification#279]
The app is really good except that I don't get notifications from the regular google calendar when I use this app.
The notifications from this app are not very visible as they get bundled together automatically.
So If I could get both notifications, then I would see the gcal notification when an event happens, and in case I miss it, I can still see this app's notification still there.

**Comment by quarck** [comment]
You can disable grouping of notifications in the settings.  The whole purpose of this app is to replace original notifications,  not designed to work together.
