### ISSUE TITLE
Open events with another calendar

### ISSUE THREAD

**Issue by andreapx** [quarck/CalendarNotification#280]
Since some updates ago, it was possible to choose with which calendar to open reminded events, now it just opens them with the stock calendar app (which is not the default)

**Comment by quarck** [comment]
This is not related to the app.  It is a system setting somewhere on your device.

**Comment by andreapx** [comment]
Actually it doesn't seem so.
When I click on the pencil 
![screenshot_calendar_notifications_20181010-115158](https://user-images.githubusercontent.com/13846728/46728941-43cc1e00-cc84-11e8-965b-19923846ddad.png)
It brings me here
![screenshot_calendar_notifications_20181010-115203](https://user-images.githubusercontent.com/13846728/46728973-5ba3a200-cc84-11e8-9977-c6fbc2b25632.png)
and that is not my default calendar.
In fact when I click on the 3 dots and then on "Open in calendar", it brings me on my default calendar (Etar).
