### ISSUE TITLE
CalendarNotification not installable on Nougat

### ISSUE THREAD

**Issue by sphh** [quarck/CalendarNotification#282]
I noticed that the updates of CalendarNotification cannot be installed on my Nougat Android.

- Is there a special reason that it is not available anymore?
- Is there a workaround so that I can install the latest version of CalendarNotification on older Android systems?
- Do you plan to support older Android versions again?

I would be very happy to use this wonderful and really helpful program on my older Android, so please keep on you good work!

**Comment by woj-tek** [comment]
Just run into same issue via F-Droid -- it offered update but failed due to incompatibility.

**Comment by Peque** [comment]
Same here. It seems the problem came in with the "[Back port from Calendar Notifications NG](98634331c09889962c16d6a6619e50b0074ec7ee)".

@quarck Would it be possible to upload an "Old Calendar Notifications" app version to F-Droid with the old code? :innocent: It seems F-Droid [only keeps the latest versions](https://f-droid.org/en/packages/com.github.quarck.calnotify/) and, threrefore, the latest updates overwrote all non-Oreo-compatible versions.

**Comment by quarck** [comment]
To be honest - it is real pain to support new notifications (with channels, etc) and old (pre-Oreo), so new builds are targeting Oreo as min sdk. 

I wasn't aware than f-droid didn't keep much of previous apks, they used to keep the entire history in the past. On Google Play users who are still using old devices would be getting older apk that supports pre-Oreo android versions.

**Comment by woj-tek** [comment]
They usually do, but after taking a look - it only shows last 3 versions without any time limitations.
So for CalendarNotificationPlus I can see 4.0.1 / 4.0.2 / 4.0.3.

The problem though (for me) is not that I can't install it anymore (it's already installed) but quite often I get notificaiton that ClendarNotification failed to install.

Not sure how it works exactly from F-droid perspective but maybe having two branches and having "CalendarNotification (legacy)" using code from previous/stable branch?

**Comment by quarck** [comment]
I'll try bringing support for the older versions of android back, but it might have some limited functionality compared to what you have at the moment. Current most recent version targeting Oreo has lost support for customizeable vibration patterns, LED colors, etc. (Oreo limitation). I probably will not be bringing support for these features back as it would create a completely different branch of code that I can't even test reliable anymore.

**Comment by quarck** [comment]
P.S. Meanwhile - if you can, please install this app from Google Play on older devices. Google Play version is built from exactly the same source code, the only difference are signing keys used - for Google Play I've used my own, for F-Droid f-droid is using their keys.

**Comment by woj-tek** [comment]
As I said - I think it would be more than enough to have previous version in installable state and then new version available only for Oreo ("legacy" description) - this should make it work just fine :-)

**Comment by quarck** [comment]
The problem with F-Droid - is that I don't have any control over it. I've submitted request to add my app into the repository once and that's it. They maintain repository on their own without my interaction. F-Droid typically monitors github and pulls source code for all the new releases, then they build their own apk and publish it there without any input from me or any form of interaction with me. (it is opensource after all - they don't have to ask). 

Another problem with uploading old versions - I don't have apks left on my local devices. And building the old version of code with current version of Android Studio isn't straightforward - it seems to be not compatible anymore, so even f-droid would not be able to build it easily given source code of the old version (which is easy to get).
Android Studio will only build the old source code if I update target SDK to Oreo or higher, and then it means it needs all the changes from 4.0.* to make it actually work correctly ;) 

So it is complicated.

**Comment by Bubu** [comment]
>  It seems F-Droid only keeps the latest versions and, threrefore, the latest updates overwrote all non-Oreo-compatible versions.

Enable the f-droid archive repo in settings. You'll get all the versions ever published there.

**Comment by quarck** [comment]
Just a status update: 

I believe this is now partially resolved. 

Even further, it was my decision to pull this app off the Google Play Store, so F-droid is not the primary and the only distribution channel. 
Since I don't have to fit into API level requirements of Google Play, I'll try dropping Target SDK level back and bring back more functionality that was killed by "Oreo compatibility" changes.

**Comment by quarck** [comment]
But it will take time - "post oreo" code  has now significantly diverged from "pre oreo", so don't expect anything very soon

**Comment by woj-tek** [comment]
> Since I don't have to fit into API level requirements of Google Play, I'll try dropping Target SDK level back and bring back more functionality that was killed by "Oreo compatibility" changes.

Best news ever! Thank you so much for your work!

**Comment by quarck** [comment]
Finally, the release 5.0.0-novaespero was created today. F-Droid should pick it up and publish in a few days, it brings everything (or at least most) back.
