### ISSUE TITLE
New GitLab page returns 404 error

### ISSUE THREAD

**Issue by protist** [quarck/CalendarNotification#283]
The description for this GitHub project says:

> Development is frozen, all the new features would be added into the new fork - Calendar Notifications NG (https://gitlab.com/quarck/CalendarNotificationNG/)

However, [this page](https://gitlab.com/quarck/CalendarNotificationNG/) returns a 404 error.

> The page could not be found or you don't have permission to view it.

**Comment by quarck** [comment]
Actually it is all back here, so ignore gitlab
