### ISSUE TITLE
Duplicate notifications

### ISSUE THREAD

**Issue by jewels3000** [quarck/CalendarNotification#288]
If there is a recurring reminder such as a daily reminder, is there a way to only have this notify me once and not create a new entry for every single time?

I am using a shared calendar and therefore can't just create one entry which would work for me. They have to be daily entries but obviously this is clogging up my notifications.

**Comment by sopos** [comment]
even in the shared calendar the notifications are personal, I guess, so you should be able to remove it if you do not want to be notified

**Comment by quarck** [comment]
With recurring events, both underlying Android Calendar Provider and the app itself handle each occurrence of such event as a separate entry, and it is at the moment baked quite deeply into the architecture of the app. Change to add an option to ignore repeating events would be quite hacky and will break lots of stuff - don't have courage doing that.
