### ISSUE TITLE
Duplicate notifications from calendar app

### ISSUE THREAD

**Issue by jahlborn** [quarck/CalendarNotification#290]
I love this app. The notifications for this app are everything I want. The bug, however, is that the Google calendar notifications still show up, so I get double notifications for every event. Is this expected behavior or a bug? I'm on Android 7.1.1

**Comment by sopos** [comment]
you need to switch off other apps (like calendar app) notifications manually, than you're fine

**Comment by jahlborn** [comment]
interesting.  i thought that this app would need those notifications enabled in order to work (i guess it reads the calendar directly instead).  turning them off did the trick!  might be nice to note that somewhere in the instructions?  thanks again for a great app.
