### ISSUE TITLE
Recognizing Google Calendar events but not reminders

### ISSUE THREAD

**Issue by nelsonov** [quarck/CalendarNotification#294]
Samsung Galaxy S8 Android 8.0.0

Calendar Notifications works as intended for Google Calendar events, but it ignores Google Calendar reminders. This forces me to leave notifications enabled for the Google app. This results in duplicate notifications for events: one from the Google apo and one from your app. The reminder notifications are coming from the Google app.

**Comment by quarck** [comment]
Google Reminders aren't actually in the android system calendar, they are completely enclosed inside the Google app - nothing can be done here.
