### ISSUE TITLE
Update to Google Calendar Brakes Calindar Notification App

### ISSUE THREAD

**Issue by swordstool** [quarck/CalendarNotification#295]
I just updated Google Calendar app on my Huawei Mate 10 Pro, and now I cannot open the Calendar Notification app. It just immediately closes. I've tried restarting the phone too. I've lost a lot of snoozed notifications if this isn't resolved =(

**Comment by quarck** [comment]
Any chance you can capture logcat output from your device from the moment of the crash?

**Comment by swordstool** [comment]
Unfortunately I had to uninstall and reinstall it. It works fine now, but I
lost a bunch of snoozed events, which really sucks.

**Comment by quarck** [comment]
Sorry to hear that, but with resources and time I have for this app it is hard to make it fully reliable in 100% cases on 100% device... Section 15 is there for a reason in a GPLv3 license text :)

**Comment by quarck** [comment]
Closing for now until more details available.
