### ISSUE TITLE
Info: right files for translation contribution 

### ISSUE THREAD

**Issue by StarCruiser75** [quarck/CalendarNotification#296]
Hi, I would like to contribute with Italian translation.
Is it correct if I translate "strings.xml" and "arrays.xml" that I find in "CalendarNotification/app/src/main/res/values/" and place them in a "values-it" folder?
Thanks, Paolo

**Comment by ramack** [comment]
this is an interesting question. I also saw, that the German translation is not fully complete, I can contribute that. I a PR with the file changes the right approach, or do you use some translation tool like crowdin or weblate or whatever. (If not, I'd propose to do so, as this really simplifies the translations and even non-developers can help then)
