### ISSUE TITLE
Old events keep popping up

### ISSUE THREAD

**Issue by slackhead** [quarck/CalendarNotification#299]
I'm bombarded by events from last week all the time, as well as one from earlier today. I keep dismissing them but they keep coming back.

Any ideas?

**Comment by slackhead** [comment]
I'm using ICSDroid to sync from a calcurse exported calendar on my laptop every 5 minutes.
In CN/behavior I have set it to handle events with no reminders, since these exports don't have any.  That way I only have to update calcurse on my laptop and everything will be auto-updted on my phone.

Two problems:

Every time ICSDroid syncs, CN repeats all the notifications for today and the past week.
Dismissing or muting doesn't stop it.  They just keep reappearing, so I end up with a list of clones in status.

I don't know where the setting to show events from the past week is.  I can't find it anywhere in the normal calendar (android 4.3).  The only other calendar I have is business calendar, but that has no settings for notifications.

By the way, the ICS calendar is read-only, if that's a problem? I'll try importing them into a r/w calendar and see if it helps.

Great app by the way!

**Comment by quarck** [comment]
Hi there. 
Apologise for a delayed response -- to much is going on in real life. 

I think what's happening here is on every cycle of sync, local calendar provider on your device assigns a new event IDs for all the events for some reason, and that triggers CN to fire all the reminders again as with the current logic it believes these are the new events. (I've seen such behavior with WebDAV-based sync adapters; in contrast google calendar sync adapter preserves event IDs for the existing events, thus not triggering multiple fires). 

I don't really have a good solution for this at the moment. You can theoretically disable manual calendar rescan, but it will also kill the functionality of reminding about events without reminders. 
But if manual calendar rescan is enabled - then the combination of calendar id / event id / start time is basically everything I can think of as a unique identifier of the particular instance of the event. If the old event gets the new event id - I don't know how to tell if this is an old with the new ID or it is an event app did miss for some weird reason (like being killed by the battery optimizer for a day - happens on some user devices). 

well, it is not exactly true - there is one possible option - generate a MD5 (or similar) hash of the start time, title and content and keep it in the local list of already handled events. But CN actually already attempts that and for some reason it don't seems to be working (implementation is around "WasHandledCache.kt" / "WasHandledCacheImplV1.kt" files). At the moment the MD5-hashing function is defined as: 
`
fun EventAlertRecord.essenceMD5() =
        ("${title.length},${desc.length},${location.length}," +
                "$startTime,$instanceStartTime,$isAllDay," +
                "$title,$desc,$location").md5()
`
Possibly startTime keeps moving, or sync adapter is adding something in the description... 

I'll try to get back to this issue when I have more time - no promises here.

**Comment by quarck** [comment]
Can you please check if 5.0.0 is any better in this context? (It should get published on f-droid in a few days)

**Comment by slackhead** [comment]
I will if I remember, but I've already paid for an alternative to ICSDroid that works well with CN now.

**Comment by quarck** [comment]
Do not worry then. Thanks for getting back to me. Since the primary issue is in sync provider, I'll close this one.
