### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Garfius** [quarck/CalendarNotification#300]
Oneplus 5
Android 8.1
Only shows blank screen.
No event notifications to display

**Comment by quarck** [comment]
So do you receive your calendar notifications via your main calendar app instead? 
What is the version of the app are you using?

**Comment by Garfius** [comment]
Here i attach screenshots of the issue.

No sound at all.



Missatge de Sergey Parshin <notifications@github.com> del dia dj., 21 de
febr. 2019 a les 0:22:

**Comment by Garfius** [comment]
Sorry, the previous mail was not meant to you.
This one is.

My calendar is full, the app is empty.

Oneplus 5 Android 8

Please fix it.

tx.

Missatge de Sergey Parshin <notifications@github.com> del dia dj., 21 de
febr. 2019 a les 0:22:

**Comment by quarck** [comment]
1. What is the application version you are using? 
2. Can you collect logcat logs from your device at the moment when you expected event to fire and Calendar Notifications did not fire it?
