### ISSUE TITLE
Notification for all-day-events

### ISSUE THREAD

**Issue by Petbue** [quarck/CalendarNotification#301]
All-day-events will be notified at midnight (or when silent time ends), so far so good. But there appears a second notification at 9am and I don't know why. Definitely I do not snooze the first notification until 9am..., it's  really a second one. Knows anybody why it happens and how I can get rid of it?
Thanks, Peter

**Comment by quarck** [comment]
That's probably how you (or your calendar app) has created these events, I'd guess. Every event has a list of reminder times attached to it, and it can have more than one.
