### ISSUE TITLE
App Stopping on Galaxy s8

### ISSUE THREAD

**Issue by vatermann** [quarck/CalendarNotification#303]
I've been using the app with this device for a couple of months now with great results.  In the last week or so, the app won't even open, and obviously doesn't work.  Please advise on what to do.

**Comment by quarck** [comment]
Would you be able to collect some logcat logs from the device from the
moment of the crash?

**Comment by vatermann** [comment]
I'm happy to help, but I'm not a developer so I don't know how.

**Comment by quarck** [comment]
Here is a good article by citrix:

https://support.citrix.com/article/CTX232375

Please do not upload the logs to github, send me directly but email to
quarck@gmail.com citing the issue number.

**Comment by vatermann** [comment]
Hi Sergey,

I went ahead and uninstalled then reinstalled the app, and it's working
fine now.  I wonder if my phone settings were blocking permissions for the
app or something.  Thanks for the quick response and for making a great
app.
