### ISSUE TITLE
Notifications won't go away

### ISSUE THREAD

**Issue by shvt** [quarck/CalendarNotification#306]
The notifications stays there and doesn't go away after I edit the event to another time.  This is when I press the edit button and it edits within the calendar app.  I'm using Samsung galaxy S10+ on android version 9.

**Comment by quarck** [comment]
Too little details.

Anyway, due to limitations of Android 8 an higher, auto-dismiss of event edited in an external calendar app is not expected to work very well. Thank Google for this.
