### ISSUE TITLE
Oppo F9 pro notification firing issue

### ISSUE THREAD

**Issue by Tarundembla** [quarck/CalendarNotification#307]
Hi
Not firing if I close the app 
even after background running is activated and auto startup is on in Oppo F9 pro.

Firing only when app is running in the background.
Need to keep it minimised all the time to fire the notification else it's not working.

Please help.

**Comment by quarck** [comment]
From the description of the issue it is not very clear what are you doing. Would you be able to record some sort of a video may be with the demo of the issue? 
It would also help if you could collect adb logs from the device.  Here is a good article by citrix on how to do it: https://support.citrix.com/article/CTX232375 . Please do not upload the logs to github, send me directly but email to quarck@gmail.com citing the issue number. Also please inspect the logs before sending as sometimes other apps might leak private information into the log.

Also can you please provide your android version and app version?

**Comment by quarck** [comment]
Closing until further details provided
