### ISSUE TITLE
Grouping no longer goes away

### ISSUE THREAD

**Issue by jahlborn** [quarck/CalendarNotification#312]
Thanks for a great app. I love it. However, ever since the latest update a few weeks ago, the grouping doesn't quite work correctly. When there are multiple notifications grouped and I snooze the last notification, the group notification is still there (without an actual event). Hope you can fix this.

**Comment by quarck** [comment]
It would be helpful to know application version / Android version / device model

**Comment by jahlborn** [comment]
app version 4.0.16
android 8.0.0
moto g6 play

**Comment by quarck** [comment]
In theory this should be fixed in 5.0.2 already. (new version is only on F-Droid).

**Comment by jahlborn** [comment]
i don't know all the ins and outs about how android app version releases happen.  when might this version land on my phone?

**Comment by quarck** [comment]
As I've said earlier - "new version is only on F-Droid". Make sure you have app installed from F-Droid.

**Comment by jahlborn** [comment]
sorry, i was not previously aware that fdroid was an alternative app store.  trying the latest version from there now, thanks.

**Comment by jahlborn** [comment]
Thanks, latest version works great!
