### ISSUE TITLE
Cancelled events still popup

### ISSUE THREAD

**Issue by Kriknav** [quarck/CalendarNotification#321]
I have the option turned on to not notify on cancelled events. The default calendar notification does not show up for these, but Calendar Notifications notifies me still. For reference these are calendar events that Blue mail is syncing from and MS Exchange server and appear to mark them as canceled by altering the title to start with "Canceled: ". Maybe we can have an option to ignore events based on title patterns?

**Comment by quarck** [comment]
Settings -> Behavior -> "Ignore Declined events" and "Ignore Cancelled events"

**Comment by Kriknav** [comment]
Both are enabled already, still same issue.
