### ISSUE TITLE
legacy?  is there a new version? 

### ISSUE THREAD

**Issue by deanhiller** [quarck/CalendarNotification#324]
calendar notifications plus is marked legacy?  Is there a new one?  Is there a pay-for version?

Also, do you have one that works with misfit vapor 2 watch?  (Trying to get notifications only through watch so it vibrates on my wrist and doesn't sound the whole office).

thanks,
Dean

**Comment by quarck** [comment]
It is only legacy on Google Play as google play is a pain in the ... to support. 

All new functionality would be available on F-Droid only. [https://f-droid.org/en/packages/com.github.quarck.calnotify/]. 

But please keep in mind - this is an open source project that is maintained when I have time for it. It is not a source of income or anything... So I can promise absolutely nothing about timelines when things would get fixed / available / etc
