### ISSUE TITLE
When installed from F-Droid, does not ask for Calendar access

### ISSUE THREAD

**Issue by aibaraiduas** [quarck/CalendarNotification#4]
When Calendar Notification Plus is installed via both F-Droid and Google Play, it does not ask for permission to access the calendar. It therefore doesn't work until it is manually given that permission via Android's settings. Tested on a Nexus 5 running Android 6.0.1.

(Sorry, just realized it does the same thing with Google Play, hence the incorrect title.)

**Comment by quarck** [comment]
Unfortunately I don't have Android 6.0.1 device handy. Please let me know if this apk works for you, and then I close the issue: 

https://dl.dropboxusercontent.com/u/25074445/cnotify/CalendarNotificationPlus_1.0.6.apk

(Signed with Google Play keys, this version would be available on Google Play in a few hours)

**Comment by quarck** [comment]
I did a test on simulator, it seems working OK. please reopen if you still have it broken.

**Comment by aibaraiduas** [comment]
Yep, your fix works great. Thank you!
