### ISSUE TITLE
Add notification reminders

### ISSUE THREAD

**Issue by quarck** [quarck/CalendarNotification#6]
As described / requested by users: 

> Allow the user to set a custom notification reminder in minutes that will trigger the notification again if it wasnt snoozed or dismissed.
> So if the user doesnt interact with the notification for 5 min (for example) it will trigger the alarm again.

and

>  if the notification start because an event in the calendar, the ringtone should repeat it self until the user intervene.
> The parameters that in your program will be:
> 1. How many time the ringtone will repeat it self, for example 2 time or indefinitely until the user demist or delay the event.
> 2. The delay between repeat ringtone notification.

**Comment by quarck** [comment]
Requested by Hananel and Nils

**Comment by gdevenyi** [comment]
+1 on this,  this would bring android phones to the same level of features as my palm z22

**Comment by quarck** [comment]
Reminders were added in ecb64511138328654598e728df13068ec7b14adf, please re-open if there are any issues with them
