### ISSUE TITLE
TODO: Add "swipe-to-dismiss"

### ISSUE THREAD

**Issue by heX16** [quarck/CalendarNotification#75]
Remove notification by swipe (as other notify).

http://stackoverflow.com/questions/14671453/catch-on-swipe-to-dismiss-event

**Comment by quarck** [comment]
Hi, 
Thanks for idea, but it is actually already possible with this app. If you disable "Show dismiss button" in the settings, then you would be able to dismiss notifications with just swiping them off. 
Please confirm if that's what you expect, and then I would close this issue.

**Comment by quarck** [comment]
P.S. It would make sense adding some "initial setup screen" for new users so they can choose behavior they want

**Comment by quarck** [comment]
I would assume that's what you wanted, so would close it for now
